feat: Поле `submitFormBody` может быть реактивным
Pacific-Agency/nuxt-utils pull request #210
Opened 2024-10-21 15:40 UTC by f4lz

### 📝 Описание изменений
Теперь поле `submitFormBody` может быть реактивным

2024-10-21 15:50 UTC, ExEr7um requested changes

2024-10-21 15:50 UTC, ExEr7um commented on src/runtime/composables/useSubmitForm.ts
> +  submitFormBody: Record<string, string> | Ref<Record<string, string>>
Лучше используй тип `MaybeRef`

2024-10-21 15:50 UTC, ExEr7um commented on src/runtime/composables/useSubmitForm.ts
> +  options?: Partial<SubmitFormOptions> | Ref<Partial<SubmitFormOptions>>
Лучше используй тип `MaybeRef`

2024-10-21 15:50 UTC, ExEr7um commented on src/runtime/composables/useSubmitForm.ts
> +      const unReactiveBody = unref(unReactiveOptions.submitFormBody)
Не создавай эту переменную, сразу обращайся просто

2024-10-21 15:50 UTC, ExEr7um commented on src/runtime/composables/useSubmitForm.ts
> +    const unReactiveOptions = unref(options)
Вместо этого перенеси строчку `const params = defu(options, defaults)` сюда, в ней сделай `unref`, чтобы новых переменных не плодить

2024-10-21 16:04 UTC, f4lz commented on src/runtime/composables/useSubmitForm.ts
> +    const unReactiveOptions = unref(options)
Не понял, типо так? 
![image](https://github.com/user-attachments/assets/84804a2c-fc4d-4159-845b-8ad8e349f82f)

2024-10-22 07:59 UTC, ExEr7um commented
@f4lz а изменения где?

2024-10-22 08:51 UTC, f4lz commented
> @f4lz а изменения где?

Я отметил, чтобы ты коммент глянул)

2024-10-22 10:56 UTC, ExEr7um commented on src/runtime/composables/useSubmitForm.ts
> +    const unReactiveOptions = unref(options)
Да

2024-10-24 06:58 UTC, ExEr7um requested changes

2024-10-24 06:58 UTC, ExEr7um commented on src/runtime/composables/useSubmitForm.ts
> +    if (optionsRaw?.submitFormBody) {
Если `submitFormBody` будет `ref`, то это условие всегда будет истинным, даже когда там пусто. Нужно `unref` сделать перед этим

2024-10-24 13:46 UTC, merged